=== jonavillegas/TranzactChallenge/APIChallengeTranzact/src/test/java/schema/countryBy/countryBy[200]_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Welcome",
  "definitions": {
    "Welcome": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "topLevelDomain": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "alpha2Code": {
          "type": "string"
        },
        "alpha3Code": {
          "type": "string"
        },
        "callingCodes": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "integer"
          }
        },
        "capital": {
          "type": "string"
        },
        "altSpellings": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "region": {
          "type": "string"
        },
        "subregion": {
          "type": "string"
        },
        "population": {
          "type": "integer"
        },
        "latlng": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "demonym": {
          "type": "string"
        },
        "area": {
          "type": "integer"
        },
        "gini": {
          "type": [
            "integer",
            "number"
          ]
        },
        "timezones": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "borders": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nativeName": {
          "type": "string"
        },
        "numericCode": {
          "type": "string",
          "format": "integer"
        },
        "currencies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Currency"
          }
        }
      },
      "required": [
        "alpha2Code",
        "alpha3Code",
        "altSpellings",
        "area",
        "borders",
        "callingCodes",
        "capital",
        "currencies",
        "demonym",
        "gini",
        "latlng",
        "name",
        "nativeName",
        "numericCode",
        "population",
        "region",
        "subregion",
        "timezones",
        "topLevelDomain"
      ],
      "title": "Welcome"
    },
    "Currency": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "symbol": {
          "type": "string"
        }
      },
      "required": [
        "code",
        "name",
        "symbol"
      ],
      "title": "Currency"
    }
  }
}

=== jonavillegas/TranzactChallenge/APIChallengeTranzact/src/test/java/response/countryBy/countries[GB]_responseBody.json
{
  "name": "United Kingdom of Great Britain and Northern Ireland",
  "topLevelDomain": [
    ".uk"
  ],
  "alpha2Code": "GB",
  "alpha3Code": "GBR",
  "callingCodes": [
    "44"
  ],
  "capital": "London",
  "altSpellings": [
    "GB",
    "UK",
    "Great Britain"
  ],
  "region": "Europe",
  "subregion": "Northern Europe",
  "population": 65110000,
  "latlng": [
    54,
    -2
  ],
  "demonym": "British",
  "area": 242900,
  "gini": 34,
  "timezones": [
    "UTC-08:00",
    "UTC-05:00",
    "UTC-04:00",
    "UTC-03:00",
    "UTC-02:00",
    "UTC",
    "UTC+01:00",
    "UTC+02:00",
    "UTC+06:00"
  ],
  "borders": [
    "IRL"
  ],
  "nativeName": "United Kingdom",
  "numericCode": "826",
  "currencies": [
    {
      "code": "GBP",
      "name": "British pound",
      "symbol": "Â£"
    }
  ]
}

=== jonavillegas/TranzactChallenge/APIChallengeTranzact/src/test/java/response/countryBy/countries[DE]_responseBody.json
{
  "name": "Germany",
  "topLevelDomain": [
    ".de"
  ],
  "alpha2Code": "DE",
  "alpha3Code": "DEU",
  "callingCodes": [
    "49"
  ],
  "capital": "Berlin",
  "altSpellings": [
    "DE",
    "Federal Republic of Germany",
    "Bundesrepublik Deutschland"
  ],
  "region": "Europe",
  "subregion": "Western Europe",
  "population": 81770900,
  "latlng": [
    51,
    9
  ],
  "demonym": "German",
  "area": 357114,
  "gini": 28.3,
  "timezones": [
    "UTC+01:00"
  ],
  "borders": [
    "AUT",
    "BEL",
    "CZE",
    "DNK",
    "FRA",
    "LUX",
    "NLD",
    "POL",
    "CHE"
  ],
  "nativeName": "Deutschland",
  "numericCode": "276",
  "currencies": [
    {
      "code": "EUR",
      "name": "Euro",
      "symbol": "â‚¬"
    }
  ]
}
